### PR TITLE
CIF-2298 - Menu cache flush is not working as expected

### LINKED ISSUE #646: Menu cache is flush not working as expected
### Expected Behaviour
Changing a category name in Magento should be reflected in the AEM Menu after TTL has expired.

### Actual Behaviour
TTL is set to venia/components/commerce/navigation:true:5:300.
After changing the name in magento it changed in AEM, but it took about an hour.

#### Steps to Reproduce
* Use Venia OOTB
* Change category name in Magento
* Wait for TLL (eg. 5 min) as set in config
* Check in AEM if menu item name has changed.

#### Platform and Version
* CIF 2.0
* AEM as a cloud service
* Tested only on author instance

### PR DESCRIPTION
**Pull request by LSantha**
Ensure that the resource type of the component proxy is used for cache name.
For instance currently the cache name for navigation component is: core/cif/components/structure/navigation/v1/navigation
while it's supposed to be: venia/components/commerce/navigation

## Related Issue

CIF-2298

Fixes #646.

## Motivation and Context

This was the initial behavior but internal modification changed it.

## How Has This Been Tested?

Manually, unit tests.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes and the overall coverage did not decrease.
- [X] All unit tests pass on CircleCi.
- [X] I ran all tests locally and they pass.

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java [hunk 1]
```diff
@@ -190,10 +191,13 @@ private void initModel(Resource resource, Page page, SlingHttpServletRequest req
         }
 
         this.httpHeaders = headers;
+        // In certain situations resource.getResourceType() returns an enforced resource type.
+        // We prefer the resource type of the component proxy for the cache name.
+        String cacheName = resource.getValueMap().get(ResourceResolver.PROPERTY_RESOURCE_TYPE, resource.getResourceType());
```
Comment (Buuhuu) [inline bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java:196]: This may be null, please fallback to `resource.getResourceType()` if so

Comment (LSantha) [reply bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java:196]: What may be null here?

Comment (Buuhuu) [reply bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/client/MagentoGraphqlClientImpl.java:196]: ahh mist the default, nevermind and sorry.

**Review by Buuhuu — APPROVED** [review]

**Review by mhaack — APPROVED** [review]
