### PR TITLE
CIF-2049 - implement UID support for button component and use URLProvider for the component

### LINKED ISSUE #553: Button component doesn't use UrlProvider to create product and category links
### Expected Behaviour
When using the [CIF Button (v1) component](https://github.com/adobe/aem-core-cif-components/tree/master/ui.apps/src/main/content/jcr_root/apps/core/cif/components/content/button/v1/button), I expected it to create URLs that are formatted based on what's defined in the UrlProvider OSGi config.

Expected: /content/luma/language-masters/en/category/category-page.21.html/women/tops-women

### Actual Behaviour

The behavior that I'm seeing is that it's missing the suffix and therefore breaks the special sling mapping that's set up.

Actual: /content/luma/language-masters/en/category/category-page.21.html

#### Steps to Reproduce

Drop the CIF Button on a page and link to a category from the authoring dialog.

#### Platform and Version
AEM 6.5.6

#### Logs taken while reproducing problem
ButtonImpl:
```
    private String constructUrl(final String pagePath, final String urlKey) {
        return String.format("%s.%s.html", pagePath, urlKey);
    }
```

### PR DESCRIPTION
**Pull request by mhaack**
## Description

Fixes the Button Component implementation which was very outdated.
 - add UID support 
 - use URLProvider to generate PDP/PLP links

## Related Issue

Fixes #553

CIF-2049

## How Has This Been Tested?

Extended existing unit tests and added extra unit tests.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes and the overall coverage did not decrease.
- [x] All unit tests pass on CircleCi.
- [x] I ran all tests locally and they pass.

### CODE REVIEW

File: bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/CategoryRetriever.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    CategoryRetriever(MagentoGraphqlClient client, boolean enableUIDSupport) {
+        super(client);
+        this.enableUIDSupport = enableUIDSupport;
+    }
+
+    @Override
+    protected CategoryTreeQueryDefinition generateCategoryQuery() {
+        CategoryTreeQueryDefinition categoryTreeQueryDefinition = q -> {
+            q.id().urlPath();
+            if (enableUIDSupport || categoryIdentifierType == UrlProvider.CategoryIdentifierType.UID) {
```
Comment (herzog31) [inline bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/CategoryRetriever.java:37]: You don't need this condition here. You can always query for it, since it's available with 2.4.2 and that's the min. required version.

**Review by herzog31 — APPROVED** [review]

File: bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/CategoryRetriever.java (hunk 1 above)
Comment (mhaack) [reply bundles/core/src/main/java/com/adobe/cq/commerce/core/components/internal/models/v1/button/CategoryRetriever.java]: Change it, code now always queries for uid and use it in the button component impl. This also simplifies the code a lot since `enableUIDSupport` is not needed any more.
